#!/usr/bin/env bash
# Create .env and backend/.env for Docker deployment.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/lib/common.sh"

ENV_FILE="${PROJECT_ROOT}/.env"
BACKEND_ENV="${PROJECT_ROOT}/backend/.env"
EXAMPLE="${SCRIPT_DIR}/env.example"

usage() {
  cat <<'EOF'
Usage: ./deploy/setup-env.sh [options]

Options:
  --app-url URL          Public application URL (e.g. http://203.0.113.10)
  --sa-password PASS     SQL Server SA password (generated if omitted)
  --tenant-id ID         Azure AD tenant ID
  --client-id ID         Azure AD application (client) ID
  --non-interactive      Skip prompts; use flags or defaults
  -h, --help             Show this help
EOF
}

APP_URL=""
SA_PASSWORD=""
AZURE_AD_TENANT_ID=""
AZURE_AD_CLIENT_ID=""
NON_INTERACTIVE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --app-url) APP_URL="$2"; shift 2 ;;
    --sa-password) SA_PASSWORD="$2"; shift 2 ;;
    --tenant-id) AZURE_AD_TENANT_ID="$2"; shift 2 ;;
    --client-id) AZURE_AD_CLIENT_ID="$2"; shift 2 ;;
    --non-interactive) NON_INTERACTIVE=true; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "Unknown option: $1" ;;
  esac
done

if [[ -f "${ENV_FILE}" ]]; then
  warn "${ENV_FILE} already exists — skipping creation"
  exit 0
fi

if [[ "${NON_INTERACTIVE}" == false ]]; then
  echo "Cerium Sales Tools — environment setup"
  echo

  if [[ -z "${APP_URL}" ]]; then
    read -r -p "Application URL [http://localhost]: " APP_URL
    APP_URL="${APP_URL:-http://localhost}"
  fi

  if [[ -z "${AZURE_AD_TENANT_ID}" ]]; then
    read -r -p "Azure AD Tenant ID: " AZURE_AD_TENANT_ID
  fi

  if [[ -z "${AZURE_AD_CLIENT_ID}" ]]; then
    read -r -p "Azure AD Client ID: " AZURE_AD_CLIENT_ID
  fi
fi

APP_URL="$(normalize_app_url "${APP_URL:-http://localhost}")"
[[ -n "${AZURE_AD_TENANT_ID}" ]] || die "Azure AD Tenant ID is required"
[[ -n "${AZURE_AD_CLIENT_ID}" ]] || die "Azure AD Client ID is required"

if [[ -z "${SA_PASSWORD}" ]]; then
  SA_PASSWORD="$(generate_sa_password)"
  log "Generated SQL Server SA password"
fi

if ! [[ "${SA_PASSWORD}" =~ [A-Z] ]] || ! [[ "${SA_PASSWORD}" =~ [a-z] ]] || \
   ! [[ "${SA_PASSWORD}" =~ [0-9] ]] || [[ ${#SA_PASSWORD} -lt 12 ]]; then
  die "SA_PASSWORD must be at least 12 characters with upper, lower, and digit characters"
fi

cat > "${ENV_FILE}" <<EOF
# Generated by deploy/setup-env.sh — do not commit
COMPOSE_PROJECT_NAME=cerium-sales
APP_URL=${APP_URL}
HTTP_PORT=80
SA_PASSWORD=${SA_PASSWORD}
DB_NAME=CeriumSalesTools
AZURE_AD_TENANT_ID=${AZURE_AD_TENANT_ID}
AZURE_AD_CLIENT_ID=${AZURE_AD_CLIENT_ID}
EOF
chmod 600 "${ENV_FILE}"

cat > "${BACKEND_ENV}" <<EOF
# Generated by deploy/setup-env.sh — do not commit
NODE_ENV=production
SERVER_HOST=0.0.0.0
SERVER_PORT=3000
CORS_ORIGIN=${APP_URL}
LOG_LEVEL=info

DB_HOST=sqlserver
DB_PORT=1433
DB_USER=sa
DB_PASSWORD=${SA_PASSWORD}
DB_NAME=CeriumSalesTools
DB_ENCRYPT=false
DB_TRUST_CERT=true
DB_POOL_MIN=2
DB_POOL_MAX=10

AZURE_AD_TENANT_ID=${AZURE_AD_TENANT_ID}
AZURE_AD_CLIENT_ID=${AZURE_AD_CLIENT_ID}
EOF
chmod 600 "${BACKEND_ENV}"

log "Created ${ENV_FILE}"
log "Created ${BACKEND_ENV}"
log ""
log "IMPORTANT: Register this redirect URI in Azure AD app registration:"
log "  ${APP_URL}"
log ""
log "After deployment, add optional integrations to backend/.env:"
log "  AZURE_OPENAI_ENDPOINT, AZURE_OPENAI_API_KEY, CONVERTAPI_SECRET, etc."
